# Generated by Django 4.2.11 on 2024-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dad_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('child_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeathRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=255)),
                ('date_of_death', models.DateField()),
                ('place_of_death', models.CharField(max_length=255)),
                ('cause_of_death', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DivorceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_name', models.CharField(max_length=255)),
                ('wife_name', models.CharField(max_length=255)),
                ('date_of_divorce', models.DateField()),
                ('place_of_divorce', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarriageRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=255)),
                ('bride_name', models.CharField(max_length=255)),
                ('date_of_marriage', models.DateField()),
                ('place_of_marriage', models.CharField(max_length=255)),
                ('witnesses_names', models.CharField(max_length=255)),
            ],
        ),
    ]
