# Generated by Django 4.2.11 on 2024-05-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('child_citizenship', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('dad_name', models.CharField(max_length=255)),
                ('dad_citizenship', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_citizenship', models.CharField(max_length=255)),
                ('address_registry_office', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeathRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('place_of_death', models.CharField(max_length=255)),
                ('address_registry_office', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DivorceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_name', models.CharField(max_length=255)),
                ('husband_citizenship', models.CharField(max_length=255)),
                ('husband_date_of_birth', models.DateField()),
                ('husband_place_of_birth', models.CharField(max_length=255)),
                ('wife_name', models.CharField(max_length=255)),
                ('wife_citizenship', models.CharField(max_length=255)),
                ('wife_date_of_birth', models.DateField()),
                ('wife_place_of_birth', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('date_of_divorce', models.DateField()),
                ('husband_new_surname', models.CharField(max_length=255)),
                ('wife_new_surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarriageRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=255)),
                ('groom_citizenship', models.CharField(max_length=255)),
                ('groom_date_of_birth', models.DateField()),
                ('groom_place_of_birth', models.CharField(max_length=255)),
                ('bride_name', models.CharField(max_length=255)),
                ('bride_citizenship', models.CharField(max_length=255)),
                ('bride_date_of_birth', models.DateField()),
                ('bride_place_of_birth', models.CharField(max_length=255)),
                ('groom_new_surname', models.CharField(max_length=255)),
                ('bride_new_surname', models.CharField(max_length=255)),
            ],
        ),
    ]
