# Generated by Django 4.2.11 on 2024-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marriageregistration',
            old_name='witnesses_names',
            new_name='witnesses_bride',
        ),
        migrations.AddField(
            model_name='marriageregistration',
            name='witnesses_groom',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
